### ISSUE TITLE
Canceling Extrude action does not work, gives errors

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#171] opened 2017-01-29 04:32 UTC
1. new cube
1. select face
1. click extrude
1. click "cancel"

The extrude is kept, and errors show:
`Error: d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:606: TypeError: Cannot read property '3' of undefined
Error: TypeError: Cannot read property '3' of undefined
Error:     at AddEdgeToFaceCommand.RemoveEdge (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:606:56)
Error:     at AddEdgeToFaceCommand.Undo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:622:14)
Error:     at ExtrudeCommand.ExecuteAtomicCommand (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:70:16)
Error:     at ExtrudeCommand.Execute (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:91:22)
Error:     at ExtrudeCommand.Execute (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\ExtrudeCommand.js:175:15)
Error:     at ExtrudeCommand.Undo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:101:14)
Error:     at CommandManager.Undo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\CommandManager.js:118:26)
Error:     at CommandManager.PostUndo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\CommandManager.js:138:22)
Error:     at ProBuilder_C10.PostUndo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\ProBuilder.js:572:29)
Error:     at CancelExtrude.global.$execEditor (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\PBGUI.js:379:35)`

**Comment by arthursw** [comment] 2017-01-31 17:04
Could not reproduced, maybe it has been fixed in previous commits?

**Closed by arthursw** 2017-01-31 17:04 UTC
Labels: Bug
