### ISSUE TITLE
Unable to extrude more than one Face translation

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#172] opened 2017-01-29 05:04 UTC
1. new cube
1. move face a few times
1. undo- first one works
1. undo again- does not work, errors show up:

`Error: d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:606: TypeError: Cannot read property '3' of undefined
Error: TypeError: Cannot read property '3' of undefined
Error:     at AddEdgeToFaceCommand.RemoveEdge (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:606:56)
Error:     at AddEdgeToFaceCommand.Undo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:622:14)
Error:     at TransformCommand.ExecuteAtomicCommand (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:70:16)
Error:     at TransformCommand.Execute (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:91:22)
Error:     at TransformCommand.Execute (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\TransformCommand.js:41:15)
Error:     at TransformCommand.Undo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:101:14)
Error:     at CommandManager.Undo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\CommandManager.js:118:26)
Error:     at CommandManager.PostUndo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\CommandManager.js:138:22)
Error:     at ProBuilder_C17.PostUndo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\ProBuilder.js:572:29)`

**Comment by arthursw** [comment] 2017-01-31 17:07
Could not reproduce, maybe it has been fixed by previous commits?

**Closed by arthursw** 2017-01-31 17:07 UTC
Labels: Bug
